#!/bin/bash
exec 2>&1
# http://www.hnwatcher.com/r/1539872/Using-Runit-in-a-Docker-Container
source /etc/envvars
exec /usr/bin/fastcgi-mono-server4 /applications=/:$APP_ROOT /socket=unix:/tmp/fastcgi.socket /printlog=True
